<?php

namespace App\Tests\Service\Parser;

use App\Service\Parser\LogFileParserService;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

class LogFileParserServiceTest extends KernelTestCase
{

    public function setUp(): void
    {
        $fileFinderService = new LogFileParserService::class;
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testGetAllFilesByType(LogFileParserService $fileFinderService): void
    {
    }

    public function testParseColumns(): void
    {
    }

    public function test__construct(): void
    {
    }
}
